
name: draft-new-release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Draft New Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false