
name: Publish New Release

on:
  push:
    tags:
      - "v*"

jobs:
  new-release:
    name: "Publish New Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
